name: Deploy Action

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Authorization Model
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy using a file
        uses: openfga/action-openfga-deploy@v0.1.1
        with:
          api-url: http://localhost:8080
          api-token: ${{ secrets.OPENFGA_API_TOKEN }}
          store-id: ${{ secrets.OPENFGA_STORE_ID }}
          model-file-path: openfga/schemas/lms.fga
